version: 0.2

env:
  variables:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
phases:
  install:
    commands:
      - cd services/bar-service/
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy -s $STAGE
