service: apig-service

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  stackTags:
    service: ${self:service}-${self:custom.stage}
  region: us-east-1
  logRetentionInDays: 60
  logs:
    restApi: true
  
resources:
    
plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts